name: Build and deploy Python project to Azure Function App - ups-track

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.12'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 'Resolve Project Dependencies Using Pip'
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      - name: 'Create deployment package'
        run: |
          zip -r deployment.zip . -x ".git/*" ".github/*" "*.pyc" "__pycache__/*" ".venv/*"

      - name: 'Upload artifact for deployment job'
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: deployment.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: 'Download artifact from build job'
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: 'Deploy to Azure Function App using ZIP Deploy'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ups-track'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_X1 }}
          package: deployment.zip
