name: Build and deploy Python project to Azure Function App - ups-track

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.12'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Prepare build folder
      run: |
        mkdir build
        cp -r * build/
        cp -r .funcignore .python_packages host.json requirements.txt build/ || true

    - name: Deploy to Azure Functions
      uses: Azure/functions-action@v1
      with:
        app-name: 'ups-track'
        slot-name: 'Production'
        package: './build'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9EE7793826884313A966F3AF8CE575F0 }}
